name: GitHub Actions Release to DockerHub
run-name: ${{ github.actor }} is deploying a release.
on:
  release:
    types: [published]


jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }} 
      - name: Run Tests
        run: docker build --target=test -t test-app .
      - name: Create Runtime container
        run: docker build --target=runtime -t runtime-container .
      - name: Prepare container for release
        run: docker tag runtime-container ${{ secrets.DOCKER_USER_NAME }}/my_private_repo:${{ github.event.release.tag_name }}
      - name: Push to DockerHub
        run: docker push ${{ secrets.DOCKER_USER_NAME }}/my_private_repo:${{ github.event.release.tag_name }}
      - run: echo "🍏 This job's status is ${{ job.status }}."