name: GitHub Actions Demo
run-name: ${{ github.actor }} is deploying a release
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }} 
      - name: Run Tests
        run: docker build --target=test -t test-app .
      - name: Create Runtime container
        run: docker build --target=runtime -t runtime-container .
      - run: echo "🍏 This job's status is ${{ job.status }}."

